# NOTE: This Dockerfile is only used in local.
FROM python:3.9.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV POETRY_VIRTUALENVS_IN_PROJECT false

WORKDIR /app/

# dependencies
RUN pip install -U pip poetry
COPY pyproject.toml poetry.lock /app/
RUN poetry install

COPY . /app/

EXPOSE 8000
