"""add target_text

Revision ID: 0208b2996203
Revises: fc7e7e332052
Create Date: 2022-03-26 13:31:30.110759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0208b2996203'
down_revision = 'fc7e7e332052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('target_text', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('definition', 'target_text')
    # ### end Alembic commands ###
