"""remove search index

Revision ID: bb725fb0ed5d
Revises: 0208b2996203
Create Date: 2022-03-28 11:40:20.050062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb725fb0ed5d'
down_revision = '0208b2996203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_definition___ts_vector__', table_name='definition')
    op.drop_column('definition', '__ts_vector__')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('__ts_vector__', postgresql.TSVECTOR(),
                                          sa.Computed("to_tsvector('italian', (word || ' ' || definition)",
                                                      persisted=True),
                                          autoincrement=False, nullable=True))
    op.create_index('ix_definition___ts_vector__', 'definition', ['__ts_vector__'], unique=False)
    # ### end Alembic commands ###
