"""init

Revision ID: ec5136ec9dab
Revises: 
Create Date: 2022-03-19 17:44:12.143451

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import TSVECTOR

revision = 'ec5136ec9dab'
down_revision = None
branch_labels = None
depends_on = None


class TSVector(sa.types.TypeDecorator):
    impl = TSVECTOR


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definition',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('word', sa.Unicode(), nullable=False),
                    sa.Column('slug', sa.Unicode(), nullable=False),
                    sa.Column('initial_letter', sa.String(length=1), nullable=False),
                    sa.Column('definition_type', sa.SmallInteger(), server_default=sa.text('1'), nullable=True),
                    sa.Column('qualifier', sa.String(), nullable=True),
                    sa.Column('definition', sa.UnicodeText(), nullable=True),
                    sa.Column('target', sa.Unicode(), nullable=True),
                    sa.Column('__ts_vector__', TSVector(),
                              sa.Computed("to_tsvector('italian', word || ' ' || definition)", persisted=True),
                              nullable=True),
                    sa.CheckConstraint('num_nonnulls(definition, target) > 0'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_definition___ts_vector__', 'definition', ['__ts_vector__'], unique=False,
                    postgresql_using='gin')
    op.create_index(op.f('ix_definition_initial_letter'), 'definition', ['initial_letter'], unique=False)
    op.create_index(op.f('ix_definition_slug'), 'definition', ['slug'], unique=True)
    op.create_index(op.f('ix_definition_word'), 'definition', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_definition_word'), table_name='definition')
    op.drop_index(op.f('ix_definition_slug'), table_name='definition')
    op.drop_index(op.f('ix_definition_initial_letter'), table_name='definition')
    op.drop_index('ix_definition___ts_vector__', table_name='definition', postgresql_using='gin')
    op.drop_table('definition')
    # ### end Alembic commands ###
