"""add word_ascii

Revision ID: f455c7ba107b
Revises: bb725fb0ed5d
Create Date: 2022-03-28 11:52:40.910986

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from unidecode import unidecode

revision = 'f455c7ba107b'
down_revision = 'bb725fb0ed5d'
branch_labels = None
depends_on = None


def upgrade():
    # 1- First create it as nullable
    op.add_column('definition', sa.Column('word_ascii', sa.Unicode(), nullable=True))

    conn = op.get_bind()

    # 2- then fill the values
    for definition_id, word in conn.exec_driver_sql(
            "SELECT id, word FROM definition WHERE word_ascii IS NULL"
    ).fetchall():
        w = unidecode(word).replace("'", "''")  # poor man's escaping
        conn.exec_driver_sql(f"""
        UPDATE definition
        SET word_ascii='{w}'
        WHERE id = {definition_id}
        """)

    # 3- then mark it non-nullable
    op.alter_column('definition', 'word_ascii', existing_type=sa.Unicode(), nullable=False)

    op.create_index(op.f('ix_definition_word_ascii'), 'definition', ['word_ascii'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_definition_word_ascii'), table_name='definition')
    op.drop_column('definition', 'word_ascii')
    # ### end Alembic commands ###
